name: Push

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: Cache node_modules
        id: cache-primes
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{hashFiles('**/package-lock.json')}}-node_modules
      - run: npm install
      - run: npm run build
      - run: npm test
